//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.14 at 03:53:59 PM KST 
//


package kobic.msb.server.model.jaxb;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Unmarshaller;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice minOccurs="0">
 *         &lt;element name="project">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="project-name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="accession" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="chromosome" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="mirid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="reference-genome" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="genome-name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="genome-path" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="reference-mirna" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="mirna-ver" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="samples" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="group" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="group-id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="sample" maxOccurs="unbounded" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="order" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                                 &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                                 &lt;element name="sample-path" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "project"
})
@XmlRootElement(name = "msb")
public class Msb {

    protected Msb.Project project;
    
    public Msb() {
    	this.project = new Project();
    	this.project.setSamples( this.project.getSamples() );
    	Msb.Project.Samples samples = this.project.getSamples();
    	this.project.getSamples().setGroup( samples.getGroup() );
    }

    /**
     * Gets the value of the project property.
     * 
     * @return
     *     possible object is
     *     {@link Msb.Project }
     *     
     */
    public Msb.Project getProject() {
    	if( this.project == null )
    		this.project = new Msb.Project();
        return project;
    }

    /**
     * Sets the value of the project property.
     * 
     * @param value
     *     allowed object is
     *     {@link Msb.Project }
     *     
     */
    public void setProject(Msb.Project value) {
        this.project = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="project-name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="accession" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="chromosome" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="mirid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="reference-genome" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="genome-name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="genome-path" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="reference-mirna" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="mirna-ver" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="samples" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="group" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                             &lt;element name="group-id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                             &lt;element name="sample" maxOccurs="unbounded" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="order" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                                       &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                                       &lt;element name="sample-path" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "projectName",
        "mirnaList",
        "referenceGenome",
        "referenceMirna",
        "samples"
    })
    public static class Project implements java.io.Serializable{

        /**
		 * 
		 */
		private static final long serialVersionUID = 1L;

		@XmlElement(name = "project-name")
        protected String projectName;
		@XmlElement(name = "mirna-list")
		protected Msb.Project.MiRnaList mirnaList;
        @XmlElement(name = "reference-genome")
        protected Msb.Project.ReferenceGenome referenceGenome;
        @XmlElement(name = "reference-mirna")
        protected Msb.Project.ReferenceMirna referenceMirna;
        protected Msb.Project.Samples samples;

        public void setMirnaList( Msb.Project.MiRnaList list ) {
        	this.mirnaList = list;
        }
        
        public Msb.Project.MiRnaList getMirnaList() {
        	return this.mirnaList;
        }
        /**
         * Gets the value of the projectName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProjectName() {
            return projectName;
        }

        /**
         * Sets the value of the projectName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProjectName(String value) {
            this.projectName = value;
        }



        /**
         * Gets the value of the referenceGenome property.
         * 
         * @return
         *     possible object is
         *     {@link Msb.Project.ReferenceGenome }
         *     
         */
        public Msb.Project.ReferenceGenome getReferenceGenome() {
            return referenceGenome;
        }

        /**
         * Sets the value of the referenceGenome property.
         * 
         * @param value
         *     allowed object is
         *     {@link Msb.Project.ReferenceGenome }
         *     
         */
        public void setReferenceGenome(Msb.Project.ReferenceGenome value) {
            this.referenceGenome = value;
        }

        /**
         * Gets the value of the referenceMirna property.
         * 
         * @return
         *     possible object is
         *     {@link Msb.Project.ReferenceMirna }
         *     
         */
        public Msb.Project.ReferenceMirna getReferenceMirna() {
        	if( referenceMirna == null) {
        		return new Msb.Project.ReferenceMirna();
        	}
            return referenceMirna;
        }

        /**
         * Sets the value of the referenceMirna property.
         * 
         * @param value
         *     allowed object is
         *     {@link Msb.Project.ReferenceMirna }
         *     
         */
        public void setReferenceMirna(Msb.Project.ReferenceMirna value) {
            this.referenceMirna = value;
        }

        /**
         * Gets the value of the samples property.
         * 
         * @return
         *     possible object is
         *     {@link Msb.Project.Samples }
         *     
         */
        public Msb.Project.Samples getSamples() {
        	if( this.samples == null )
        		this.samples = new Samples();
            return samples;
        }

        /**
         * Sets the value of the samples property.
         * 
         * @param value
         *     allowed object is
         *     {@link Msb.Project.Samples }
         *     
         */
        public void setSamples(Msb.Project.Samples value) {
            this.samples = value;
        }

        
        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="mirnaList" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="accession"	type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="chromosome"	type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="mirid"		type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
        		"mirna"
        })
        public static class MiRnaList implements java.io.Serializable {
        	/**
			 * 
			 */
			private static final long serialVersionUID = 1L;

			protected List<MiRnaList.MiRna> mirna;
        	
        	public MiRnaList() {
        		this.mirna = new ArrayList<MiRnaList.MiRna>();
        	}

            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="accession"		type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *         &lt;element name="chromosome"	type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *         &lt;element name="mirid"			type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
        	
        	public void setMirnaList( List<MiRnaList.MiRna> list ) {
        		this.mirna = list;
        	}
        	
        	public List<MiRnaList.MiRna> getMirnaList() {
        		return this.mirna;
        	}

            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
            		"accession",
            		"chromosome",
            		"mirid",
            })
        	public static class MiRna implements java.io.Serializable {
            	/**
				 * 
				 */
				private static final long serialVersionUID = 1L;

				protected String accession;
                protected String chromosome;
                protected String mirid;
                
                public MiRna() {
                	this.accession = "";
                	this.chromosome = "";
                	this.mirid = "";
                }

                /**
                 * Gets the value of the accession property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAccession() {
                    return accession;
                }

                /**
                 * Sets the value of the accession property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAccession(String value) {
                    this.accession = value;
                }

                /**
                 * Gets the value of the chromosome property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getChromosome() {
                    return chromosome;
                }

                /**
                 * Sets the value of the chromosome property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setChromosome(String value) {
                    this.chromosome = value;
                }

                /**
                 * Gets the value of the mirid property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getMirid() {
                    return mirid;
                }

                /**
                 * Sets the value of the mirid property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setMirid(String value) {
                    this.mirid = value;
                }
        	}
        }
        
        
        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="genome-name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="genome-path" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "genomeName",
            "genomePath"
        })
        public static class ReferenceGenome implements java.io.Serializable {

        	/**
			 * 
			 */
			private static final long serialVersionUID = 1L;

			public ReferenceGenome() {
        		this.genomeName = "";
        		this.genomePath = "";
        	}

            @XmlElement(name = "genome-name")
            protected String genomeName;
            @XmlElement(name = "genome-path")
            protected String genomePath;

            /**
             * Gets the value of the genomeName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGenomeName() {
                return genomeName;
            }

            /**
             * Sets the value of the genomeName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGenomeName(String value) {
                this.genomeName = value;
            }

            /**
             * Gets the value of the genomePath property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGenomePath() {
                return genomePath;
            }

            /**
             * Sets the value of the genomePath property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGenomePath(String value) {
                this.genomePath = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="mirna-ver" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "mirnaVer"
        })
        public static class ReferenceMirna  implements java.io.Serializable {
        	/**
			 * 
			 */
			private static final long serialVersionUID = 1L;

			public ReferenceMirna() {
        		this.mirnaVer = "";
        	}

            @XmlElement(name = "mirna-ver")
            protected String mirnaVer;

            /**
             * Gets the value of the mirnaVer property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMirnaVer() {
                return mirnaVer==null?"":mirnaVer;
            }

            /**
             * Sets the value of the mirnaVer property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMirnaVer(String value) {
                this.mirnaVer = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="group" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="group-id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="sample" maxOccurs="unbounded" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="order" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                             &lt;element name="sample-path" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "group"
        })
        public static class Samples  implements java.io.Serializable {

            /**
			 * 
			 */
			private static final long serialVersionUID = 1L;
			protected List<Msb.Project.Samples.Group> group;

            /**
             * Gets the value of the group property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the group property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getGroup().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Msb.Project.Samples.Group }
             * 
             * 
             */
            public List<Msb.Project.Samples.Group> getGroup() {
                if (group == null) {
                    group = new ArrayList<Msb.Project.Samples.Group>();
                }
                return this.group;
            }

            public void setGroup( List<Msb.Project.Samples.Group> group ) {
                this.group = group;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *         &lt;element name="group-id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *         &lt;element name="sample" maxOccurs="unbounded" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="order" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *                   &lt;element name="sample-path" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "id",
                "groupId",
                "sample"
            })
            public static class Group  implements java.io.Serializable {

                /**
				 * 
				 */
				private static final long serialVersionUID = 1L;

				protected String id;
                @XmlElement(name = "group-id")
                protected String groupId;
                protected List<Msb.Project.Samples.Group.Sample> sample;
                
                public Group() {
                	this.sample = new ArrayList<Msb.Project.Samples.Group.Sample>();
                }

                /**
                 * Gets the value of the id property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getId() {
                    return id;
                }

                /**
                 * Sets the value of the id property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setId(String value) {
                    this.id = value;
                }

                /**
                 * Gets the value of the groupId property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getGroupId() {
                    return groupId;
                }

                /**
                 * Sets the value of the groupId property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setGroupId(String value) {
                    this.groupId = value;
                }

                /**
                 * Gets the value of the sample property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the sample property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getSample().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Msb.Project.Samples.Group.Sample }
                 * 
                 * 
                 */
                public List<Msb.Project.Samples.Group.Sample> getSample() {
                    if (sample == null) {
                        sample = new ArrayList<Msb.Project.Samples.Group.Sample>();
                    }
                    return this.sample;
                }
                
                public void getSample(List<Msb.Project.Samples.Group.Sample> sample) {
                    this.sample = sample;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="order" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
                 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
                 *         &lt;element name="sample-path" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "order",
                    "name",
                    "samplePath",
                    "indexPath",
                    "sortedPath"//,
//                    "view"
                })
                public static class Sample implements java.io.Serializable {

                    /**
					 * 
					 */
					private static final long serialVersionUID = 1L;

					protected String order;
                    protected String name;
                    @XmlElement(name = "sample-path")
                    protected String samplePath;
                    @XmlElement(name = "index-path")
                    protected String indexPath;
                    @XmlElement(name = "sorted-path")
                    protected String sortedPath;
//                    protected boolean view;

                    /**
                     * Gets the value of the order property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getOrder() {
                        return order;
                    }

                    /**
                     * Sets the value of the order property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setOrder(String value) {
                        this.order = value;
                    }

                    /**
                     * Gets the value of the name property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getName() {
                        return name;
                    }

                    /**
                     * Sets the value of the name property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setName(String value) {
                        this.name = value;
                    }

                    /**
                     * Gets the value of the samplePath property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getSamplePath() {
                        return samplePath;
                    }

                    /**
                     * Sets the value of the samplePath property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setSamplePath(String value) {
                        this.samplePath = value;
                    }

                    /**
                     * Gets the value of the sortedPath property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getSortedPath() {
                        return this.sortedPath;
                    }

                    /**
                     * Sets the value of the sortedPath property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setSortedPath(String value) {
                        this.sortedPath = value;
                    }

                    /**
                     * Gets the value of the indexPath property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getIndexPath() {
                        return indexPath;
                    }

                    /**
                     * Sets the value of the indexPath property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setIndexPath(String value) {
                        this.indexPath = value;
                    }
                    
//                    public void setView( boolean view) {
//                    	this.view = view;
//                    }
//
//                    public boolean getView() {
//                    	return this.view;
//                    }
                    
                    @Override
					public Sample clone() {
                    	Sample nSample = new Sample();
                    	nSample.setName( this.getName() );
                    	nSample.setOrder( this.getOrder() );
                    	nSample.setSamplePath( this.getSamplePath() );
//                    	nSample.setView( this.getView() );
                    	nSample.setIndexPath( this.getIndexPath() );
                    	nSample.setSortedPath( this.getSortedPath() );
                    	
                    	return nSample;
                    }
                }

            }

        }

    }
    
    public static void main(String[] args) throws JAXBException {
    	JAXBContext jaxbContext = JAXBContext.newInstance( Msb.class );

		Unmarshaller jaxbUnmarshaller = jaxbContext.createUnmarshaller();
		String path = Msb.class.getResource(".").getPath();
		Msb msb = (Msb) jaxbUnmarshaller.unmarshal( new java.io.File( path + "/ProjectSample.xml") );
		
		System.out.println(msb.getProject().getMirnaList().getMirnaList().size());
    }

}
