//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.14 at 03:58:23 PM KST 
//


package kobic.msb.server.model.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the kobic.msb.server.model.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: kobic.msb.server.model.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Msb }
     * 
     */
    public Msb createMsb() {
        return new Msb();
    }

    /**
     * Create an instance of {@link Msb.Project }
     * 
     */
    public Msb.Project createMsbProject() {
        return new Msb.Project();
    }
    
    public Msb.Project.MiRnaList createMsbProjectMiRnaList() {
    	return new Msb.Project.MiRnaList();
    }
    
    public Msb.Project.MiRnaList.MiRna createMsbProjectMiRnaListMiRna() {
    	return new Msb.Project.MiRnaList.MiRna();
    }

    /**
     * Create an instance of {@link Msb.Project.Samples }
     * 
     */
    public Msb.Project.Samples createMsbProjectSamples() {
        return new Msb.Project.Samples();
    }

    /**
     * Create an instance of {@link Msb.Project.Samples.Group }
     * 
     */
    public Msb.Project.Samples.Group createMsbProjectSamplesGroup() {
        return new Msb.Project.Samples.Group();
    }

    /**
     * Create an instance of {@link Msb.Project.ReferenceGenome }
     * 
     */
    public Msb.Project.ReferenceGenome createMsbProjectReferenceGenome() {
        return new Msb.Project.ReferenceGenome();
    }

    /**
     * Create an instance of {@link Msb.Project.ReferenceMirna }
     * 
     */
    public Msb.Project.ReferenceMirna createMsbProjectReferenceMirna() {
        return new Msb.Project.ReferenceMirna();
    }

    /**
     * Create an instance of {@link Msb.Project.Samples.Group.Sample }
     * 
     */
    public Msb.Project.Samples.Group.Sample createMsbProjectSamplesGroupSample() {
        return new Msb.Project.Samples.Group.Sample();
    }

}
